Create an identity matrix of dimension 4-by-4

In [1]:
import numpy as np

identity_matrix = np.identity(4)
print(identity_matrix)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Convert a 1-D array to a 3-D array

In [2]:
import numpy as np

one_d_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

three_d_array = one_d_array.reshape((3, 1, 3))

print(three_d_array)


[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]


Convert all the elements of a numpy array from float to integer datatype
0

In [3]:
import numpy as np

float_array = np.array([1.1, 2.2, 3.3, 4.4, 5.5])

int_array = float_array.astype(int)

print(int_array)


[1 2 3 4 5]


Given a numpy array (matrix), how to get a numpy array output which is equal to the
original matrix multiplied by a scalar?

In [4]:
import numpy as np

matrix = np.array([[1, 2], [3, 4]])

scalar = 3

result = matrix * scalar

print(result)


[[ 3  6]
 [ 9 12]]


Given are 2 similar dimensional numpy arrays, how to get a numpy array output in
which every element is an element-wise sum of the 2 numpy arrays?

In [5]:
import numpy as np

array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

result = array1 + array2

print(result)


[[ 8 10 12]
 [14 16 18]]


Convert a binary numpy array (containing only 0s and 1s) to a boolean numpy array

In [6]:
import numpy as np

binary_array = np.array([0, 1, 0, 1, 1, 0])

boolean_array = binary_array.astype(bool)

print(boolean_array)


[False  True False  True  True False]


Stack 2 numpy arrays horizontally i.e., 2 arrays having the same 1st dimension (number
of rows in 2D arrays)

In [7]:
import numpy as np

array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

result_hstack = np.hstack((array1, array2))

result_concatenate = np.concatenate((array1, array2), axis=1)

print("Result using hstack:\n", result_hstack)
print("Result using concatenate:\n", result_concatenate)


Result using hstack:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
Result using concatenate:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


Stack 2 numpy arrays vertically i.e., 2 arrays having the same last dimension (number
of columns in 2D arrays)

In [8]:
import numpy as np

array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

result_vstack = np.vstack((array1, array2))

result_concatenate = np.concatenate((array1, array2), axis=0)

print("Result using vstack:\n", result_vstack)
print("Result using concatenate:\n", result_concatenate)


Result using vstack:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Result using concatenate:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Generate a sequence of numbers in the form of a numpy array from 0 to 100 with gaps
of 2 numbers


In [9]:
import numpy as np

sequence = np.arange(0, 101, 3)

print(sequence)


[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]


From 2 numpy arrays, extract the indexes in which the elements in the 2 arrays match

In [10]:
import numpy as np

array1 = np.array([10, 20, 30, 40, 50, 60])
array2 = np.array([5, 20, 35, 40, 55, 60])

matching_indexes = np.where(array1 == array2)[0]

print("Matching indexes:", matching_indexes)


Matching indexes: [1 3 5]


Output a sequence of equally gapped 5 numbers in the range 0 to 100 (both inclusive)

In [11]:
import numpy as np

sequence = np.linspace(0, 100, 5, dtype=int)

print("Sequence of equally gapped numbers:", sequence)


Sequence of equally gapped numbers: [  0  25  50  75 100]


Output a matrix (numpy array) of dimension 2-by-3 with each and every value equal to 5

In [12]:
import numpy as np

matrix = np.full((2, 3), 5)

print("2-by-3 matrix with each value equal to 5:")
print(matrix)


2-by-3 matrix with each value equal to 5:
[[5 5 5]
 [5 5 5]]


Output an array by repeating a smaller array of 2 dimensions, 10 times

In [13]:
import numpy as np

small_array = np.array([[1, 2], [3, 4]])

repeated_array = np.tile(small_array, (10, 1))

print("Array after repeating the smaller array 10 times:")
print(repeated_array)


Array after repeating the smaller array 10 times:
[[1 2]
 [3 4]
 [1 2]
 [3 4]
 [1 2]
 [3 4]
 [1 2]
 [3 4]
 [1 2]
 [3 4]
 [1 2]
 [3 4]
 [1 2]
 [3 4]
 [1 2]
 [3 4]
 [1 2]
 [3 4]
 [1 2]
 [3 4]]


Output a 10-by-10 array of random integers between 0 (inclusive) and 10 (exclusive)

In [14]:
import numpy as np

random_array = np.random.randint(0, 10, size=(10, 10))

print("10-by-10 array of random integers between 0 and 9:")
print(random_array)


10-by-10 array of random integers between 0 and 9:
[[5 7 0 2 3 2 3 8 3 9]
 [0 6 8 9 0 2 1 5 8 1]
 [8 1 5 2 8 7 0 7 3 0]
 [8 0 7 6 4 1 3 7 1 0]
 [5 5 6 9 2 1 8 6 9 5]
 [0 1 6 8 6 5 0 4 1 9]
 [1 8 3 3 5 4 8 3 6 1]
 [4 3 0 7 9 4 0 2 2 4]
 [1 1 3 0 9 0 7 2 8 9]
 [5 4 4 5 9 3 0 2 7 8]]


Given 2 numpy arrays as matrices, output the result of multiplying the 2 matrices (as a
numpy array)

In [15]:
import numpy as np

matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6]])

matrix2 = np.array([[7, 8],
                    [9, 10],
                    [11, 12]])

result = matrix1 @ matrix2

print("Result of multiplying the two matrices:")
print(result)


Result of multiplying the two matrices:
[[ 58  64]
 [139 154]]


Output the transpose of a matrix (as numpy array)

In [16]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

transpose_matrix = np.transpose(matrix)

print("Original matrix:")
print(matrix)

print("Transpose of the matrix:")
print(transpose_matrix)


Original matrix:
[[1 2 3]
 [4 5 6]]
Transpose of the matrix:
[[1 4]
 [2 5]
 [3 6]]


Output the array element indexes such that the array elements appear in the ascending
order

In [17]:
import numpy as np

array = np.array([10, 5, 8, 12, 7])

sorted_indices = np.argsort(array)

print("Original array:")
print(array)

print("Indices that would sort the array in ascending order:")
print(sorted_indices)

print("Array elements in ascending order:")
print(array[sorted_indices])


Original array:
[10  5  8 12  7]
Indices that would sort the array in ascending order:
[1 4 2 0 3]
Array elements in ascending order:
[ 5  7  8 10 12]
